
- name: instalando puppet agent em todas maquinas
  package:
   name: puppet-agent
   update_cache: yes 
   

- name: startando puppet quando for redhat
  service:
   name: puppet
   state: restarted
  when: ansible_os_family == "RedHat"

